#include<stdio.h>
#include<stdlib.h>
#include<time.h>
int random1()
{
    srand(time(NULL));
    return rand()%267+1;
}
int random2()
{
    srand(12);
    return rand()%267+1;
}
long long int fast_modular(long long int a,long long int b,long long int c)
{
    long long int arr1[1000]={0},t,l,i,arr2[1000]={0};
    t=b;
    l=0;
    while(t>0)
    {
        arr1[l++]=t%2;
        t=t/2;
    }
    arr2[0]=a%c;
    for(i=1;i<l;i++)
    {
        arr2[i]=(arr2[i-1]*arr2[i-1])%c;
    }
    t=1;
    for(i=0;i<l;i++)
    {
        if(arr1[i]==1)
        {
            t=(t*arr2[i])%c;
        }
    }
    return t%c;
}
int main()
{
    long long int p,g,x,y,ka,kb;
    int a,b;
    printf("Enter Prime Number: ");
    scanf("%lld",&p);
    printf("Enter primitive root of above prime number: ");
    scanf("%lld",&g);
    a=random1();
    printf("Private key selected by a: %d",a);
    b=random2();
    printf("\nPrivate key selected by b: %d",b);
    x=fast_modular(g,a,p);
    y=fast_modular(g,b,p);
    ka=fast_modular(y,a,p);
    printf("\nSecret Key generated by a: %lld",ka);
    kb=fast_modular(x,b,p);
    printf("\nSecret Key generated by b: %lld",kb);
    return 0;
}